services:
    app.repository.user:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    app.service.user_provider:
        class: AppBundle\Service\UserProvider
        arguments: ["@app.repository.user"]
